// <auto-generated />
namespace Portfolio_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Contact_me : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Contact_me));
        
        string IMigrationMetadata.Id
        {
            get { return "202601010748233_Contact_me"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
